//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotellingCon : DbContext
    {
        public HotellingCon()
            : base("name=HotellingCon")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Asientos> Tbl_Asientos { get; set; }
        public virtual DbSet<Tbl_AsignacionAsientos> Tbl_AsignacionAsientos { get; set; }
        public virtual DbSet<Tbl_Oficinas> Tbl_Oficinas { get; set; }
        public virtual DbSet<Tbl_Perfiles> Tbl_Perfiles { get; set; }
        public virtual DbSet<Tbl_Usuarios> Tbl_Usuarios { get; set; }
    }
}
