//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Usuarios()
        {
            this.Tbl_AsignacionAsientos = new HashSet<Tbl_AsignacionAsientos>();
        }
    
        public int Id_Usuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Apellido_Usuario { get; set; }
        public string Identificacion_Usuario { get; set; }
        public string Email_Usuario { get; set; }
        public string Telefono_Personal { get; set; }
        public string Telefono_Extension { get; set; }
        public int Id_Oficina { get; set; }
        public string Id_Perfil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AsignacionAsientos> Tbl_AsignacionAsientos { get; set; }
        public virtual Tbl_Oficinas Tbl_Oficinas { get; set; }
    }
}
