//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Oficinas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Oficinas()
        {
            this.Tbl_Usuarios = new HashSet<Tbl_Usuarios>();
        }
    
        public int Id_Oficina { get; set; }
        public string Nombre_Oficina { get; set; }
        public string Dirreccion_Oficina { get; set; }
        public string Email_Oficina { get; set; }
        public string Telefono_Oficina { get; set; }
        public int Numero_Asientos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Usuarios> Tbl_Usuarios { get; set; }
    }
}
