//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Asientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Asientos()
        {
            this.Tbl_AsignacionAsientos = new HashSet<Tbl_AsignacionAsientos>();
        }
    
        public int Id_Asiento { get; set; }
        public int Id_oficina { get; set; }
        public bool Es_Fijo { get; set; }
        public bool Tiene_Telefono { get; set; }
        public bool Tiene_Monitor { get; set; }
        public bool Tiene_Teclado_Mouse { get; set; }
        public bool Es_Especial { get; set; }
    
        public virtual Tbl_Oficinas Tbl_Oficinas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AsignacionAsientos> Tbl_AsignacionAsientos { get; set; }
    }
}
