//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Usuarios
    {
        public int Id_Usuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Apellido_Usuario { get; set; }
        public string Identificacion_Usuario { get; set; }
        public string Email_Usuario { get; set; }
        public string Telefono_Personal { get; set; }
        public string Telefono_Oficina { get; set; }
        public int Id_Oficina { get; set; }
        public int Id_Perfil { get; set; }
    
        public virtual Tbl_Oficinas Tbl_Oficinas { get; set; }
        public virtual Tbl_Perfiles Tbl_Perfiles { get; set; }
    }
}
