//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Asientos
    {
        public int Id_Asiento { get; set; }
        public int Id_oficina { get; set; }
        public bool Es_Fijo { get; set; }
        public bool Tiene_Telefono { get; set; }
        public bool Tiene_Monitor { get; set; }
        public bool Tiene_Teclado_Mouse { get; set; }
        public bool Es_Especial { get; set; }
    }
}
