//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotelling.UserApiSave {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserApiSave.UserAPISoap")]
    public interface UserAPISoap {
        
        // CODEGEN: Generating message contract since element name a from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        Hotelling.UserApiSave.SaveResponse Save(Hotelling.UserApiSave.SaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.SaveResponse> SaveAsync(Hotelling.UserApiSave.SaveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Save", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.SaveRequestBody Body;
        
        public SaveRequest() {
        }
        
        public SaveRequest(Hotelling.UserApiSave.SaveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string a;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string b;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string c;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string d;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string e;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string f;
        
        public SaveRequestBody() {
        }
        
        public SaveRequestBody(string a, string b, string c, string d, string e, string f) {
            this.a = a;
            this.b = b;
            this.c = c;
            this.d = d;
            this.e = e;
            this.f = f;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveResponse", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.SaveResponseBody Body;
        
        public SaveResponse() {
        }
        
        public SaveResponse(Hotelling.UserApiSave.SaveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveResponseBody {
        
        public SaveResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserAPISoapChannel : Hotelling.UserApiSave.UserAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAPISoapClient : System.ServiceModel.ClientBase<Hotelling.UserApiSave.UserAPISoap>, Hotelling.UserApiSave.UserAPISoap {
        
        public UserAPISoapClient() {
        }
        
        public UserAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hotelling.UserApiSave.SaveResponse Hotelling.UserApiSave.UserAPISoap.Save(Hotelling.UserApiSave.SaveRequest request) {
            return base.Channel.Save(request);
        }
        
        public void Save(string a, string b, string c, string d, string e, string f) {
            Hotelling.UserApiSave.SaveRequest inValue = new Hotelling.UserApiSave.SaveRequest();
            inValue.Body = new Hotelling.UserApiSave.SaveRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            inValue.Body.c = c;
            inValue.Body.d = d;
            inValue.Body.e = e;
            inValue.Body.f = f;
            Hotelling.UserApiSave.SaveResponse retVal = ((Hotelling.UserApiSave.UserAPISoap)(this)).Save(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.SaveResponse> Hotelling.UserApiSave.UserAPISoap.SaveAsync(Hotelling.UserApiSave.SaveRequest request) {
            return base.Channel.SaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotelling.UserApiSave.SaveResponse> SaveAsync(string a, string b, string c, string d, string e, string f) {
            Hotelling.UserApiSave.SaveRequest inValue = new Hotelling.UserApiSave.SaveRequest();
            inValue.Body = new Hotelling.UserApiSave.SaveRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            inValue.Body.c = c;
            inValue.Body.d = d;
            inValue.Body.e = e;
            inValue.Body.f = f;
            return ((Hotelling.UserApiSave.UserAPISoap)(this)).SaveAsync(inValue);
        }
    }
}
