//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotelling.UserApiSave {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserApiSave.UserAPISoap")]
    public interface UserAPISoap {
        
        // CODEGEN: Generating message contract since element name datos from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        Hotelling.UserApiSave.SaveResponse Save(Hotelling.UserApiSave.SaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.SaveResponse> SaveAsync(Hotelling.UserApiSave.SaveRequest request);
        
        // CODEGEN: Generating message contract since element name listResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/list", ReplyAction="*")]
        Hotelling.UserApiSave.listResponse list(Hotelling.UserApiSave.listRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/list", ReplyAction="*")]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.listResponse> listAsync(Hotelling.UserApiSave.listRequest request);
        
        // CODEGEN: Generating message contract since element name usr from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validacion", ReplyAction="*")]
        Hotelling.UserApiSave.validacionResponse validacion(Hotelling.UserApiSave.validacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validacion", ReplyAction="*")]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.validacionResponse> validacionAsync(Hotelling.UserApiSave.validacionRequest request);
        
        // CODEGEN: Generating message contract since element name OficinasResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Oficinas", ReplyAction="*")]
        Hotelling.UserApiSave.OficinasResponse Oficinas(Hotelling.UserApiSave.OficinasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Oficinas", ReplyAction="*")]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.OficinasResponse> OficinasAsync(Hotelling.UserApiSave.OficinasRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Asientos", ReplyAction="*")]
        Hotelling.UserApiSave.AsientosResponse Asientos(Hotelling.UserApiSave.AsientosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Asientos", ReplyAction="*")]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.AsientosResponse> AsientosAsync(Hotelling.UserApiSave.AsientosRequest request);
        
        // CODEGEN: Generating message contract since element name seatsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/seats", ReplyAction="*")]
        Hotelling.UserApiSave.seatsResponse seats(Hotelling.UserApiSave.seatsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/seats", ReplyAction="*")]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.seatsResponse> seatsAsync(Hotelling.UserApiSave.seatsRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/seatsSave", ReplyAction="*")]
        Hotelling.UserApiSave.seatsSaveResponse seatsSave(Hotelling.UserApiSave.seatsSaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/seatsSave", ReplyAction="*")]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.seatsSaveResponse> seatsSaveAsync(Hotelling.UserApiSave.seatsSaveRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReservaDatos", ReplyAction="*")]
        Hotelling.UserApiSave.ReservaDatosResponse ReservaDatos(Hotelling.UserApiSave.ReservaDatosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReservaDatos", ReplyAction="*")]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.ReservaDatosResponse> ReservaDatosAsync(Hotelling.UserApiSave.ReservaDatosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Save", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.SaveRequestBody Body;
        
        public SaveRequest() {
        }
        
        public SaveRequest(Hotelling.UserApiSave.SaveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Hotelling.UserApiSave.ArrayOfString datos;
        
        public SaveRequestBody() {
        }
        
        public SaveRequestBody(Hotelling.UserApiSave.ArrayOfString datos) {
            this.datos = datos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveResponse", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.SaveResponseBody Body;
        
        public SaveResponse() {
        }
        
        public SaveResponse(Hotelling.UserApiSave.SaveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveResponseBody {
        
        public SaveResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="list", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.listRequestBody Body;
        
        public listRequest() {
        }
        
        public listRequest(Hotelling.UserApiSave.listRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public char X;
        
        public listRequestBody() {
        }
        
        public listRequestBody(char X) {
            this.X = X;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listResponse", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.listResponseBody Body;
        
        public listResponse() {
        }
        
        public listResponse(Hotelling.UserApiSave.listResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Hotelling.UserApiSave.ArrayOfString[] listResult;
        
        public listResponseBody() {
        }
        
        public listResponseBody(Hotelling.UserApiSave.ArrayOfString[] listResult) {
            this.listResult = listResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validacion", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.validacionRequestBody Body;
        
        public validacionRequest() {
        }
        
        public validacionRequest(Hotelling.UserApiSave.validacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usr;
        
        public validacionRequestBody() {
        }
        
        public validacionRequestBody(string usr) {
            this.usr = usr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class validacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="validacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.validacionResponseBody Body;
        
        public validacionResponse() {
        }
        
        public validacionResponse(Hotelling.UserApiSave.validacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class validacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Hotelling.UserApiSave.ArrayOfString validacionResult;
        
        public validacionResponseBody() {
        }
        
        public validacionResponseBody(Hotelling.UserApiSave.ArrayOfString validacionResult) {
            this.validacionResult = validacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OficinasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Oficinas", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.OficinasRequestBody Body;
        
        public OficinasRequest() {
        }
        
        public OficinasRequest(Hotelling.UserApiSave.OficinasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class OficinasRequestBody {
        
        public OficinasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OficinasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OficinasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.OficinasResponseBody Body;
        
        public OficinasResponse() {
        }
        
        public OficinasResponse(Hotelling.UserApiSave.OficinasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OficinasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Hotelling.UserApiSave.ArrayOfString OficinasResult;
        
        public OficinasResponseBody() {
        }
        
        public OficinasResponseBody(Hotelling.UserApiSave.ArrayOfString OficinasResult) {
            this.OficinasResult = OficinasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AsientosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Asientos", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.AsientosRequestBody Body;
        
        public AsientosRequest() {
        }
        
        public AsientosRequest(Hotelling.UserApiSave.AsientosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AsientosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public AsientosRequestBody() {
        }
        
        public AsientosRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AsientosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AsientosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.AsientosResponseBody Body;
        
        public AsientosResponse() {
        }
        
        public AsientosResponse(Hotelling.UserApiSave.AsientosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AsientosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Hotelling.UserApiSave.ArrayOfString AsientosResult;
        
        public AsientosResponseBody() {
        }
        
        public AsientosResponseBody(Hotelling.UserApiSave.ArrayOfString AsientosResult) {
            this.AsientosResult = AsientosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class seatsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="seats", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.seatsRequestBody Body;
        
        public seatsRequest() {
        }
        
        public seatsRequest(Hotelling.UserApiSave.seatsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class seatsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public seatsRequestBody() {
        }
        
        public seatsRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class seatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="seatsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.seatsResponseBody Body;
        
        public seatsResponse() {
        }
        
        public seatsResponse(Hotelling.UserApiSave.seatsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class seatsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Hotelling.UserApiSave.ArrayOfString seatsResult;
        
        public seatsResponseBody() {
        }
        
        public seatsResponseBody(Hotelling.UserApiSave.ArrayOfString seatsResult) {
            this.seatsResult = seatsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class seatsSaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="seatsSave", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.seatsSaveRequestBody Body;
        
        public seatsSaveRequest() {
        }
        
        public seatsSaveRequest(Hotelling.UserApiSave.seatsSaveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class seatsSaveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Hotelling.UserApiSave.ArrayOfString data;
        
        public seatsSaveRequestBody() {
        }
        
        public seatsSaveRequestBody(int id, Hotelling.UserApiSave.ArrayOfString data) {
            this.id = id;
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class seatsSaveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="seatsSaveResponse", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.seatsSaveResponseBody Body;
        
        public seatsSaveResponse() {
        }
        
        public seatsSaveResponse(Hotelling.UserApiSave.seatsSaveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class seatsSaveResponseBody {
        
        public seatsSaveResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReservaDatosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReservaDatos", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.ReservaDatosRequestBody Body;
        
        public ReservaDatosRequest() {
        }
        
        public ReservaDatosRequest(Hotelling.UserApiSave.ReservaDatosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReservaDatosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public ReservaDatosRequestBody() {
        }
        
        public ReservaDatosRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReservaDatosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReservaDatosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Hotelling.UserApiSave.ReservaDatosResponseBody Body;
        
        public ReservaDatosResponse() {
        }
        
        public ReservaDatosResponse(Hotelling.UserApiSave.ReservaDatosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReservaDatosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Hotelling.UserApiSave.ArrayOfString[] ReservaDatosResult;
        
        public ReservaDatosResponseBody() {
        }
        
        public ReservaDatosResponseBody(Hotelling.UserApiSave.ArrayOfString[] ReservaDatosResult) {
            this.ReservaDatosResult = ReservaDatosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserAPISoapChannel : Hotelling.UserApiSave.UserAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserAPISoapClient : System.ServiceModel.ClientBase<Hotelling.UserApiSave.UserAPISoap>, Hotelling.UserApiSave.UserAPISoap {
        
        public UserAPISoapClient() {
        }
        
        public UserAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hotelling.UserApiSave.SaveResponse Hotelling.UserApiSave.UserAPISoap.Save(Hotelling.UserApiSave.SaveRequest request) {
            return base.Channel.Save(request);
        }
        
        public void Save(Hotelling.UserApiSave.ArrayOfString datos) {
            Hotelling.UserApiSave.SaveRequest inValue = new Hotelling.UserApiSave.SaveRequest();
            inValue.Body = new Hotelling.UserApiSave.SaveRequestBody();
            inValue.Body.datos = datos;
            Hotelling.UserApiSave.SaveResponse retVal = ((Hotelling.UserApiSave.UserAPISoap)(this)).Save(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.SaveResponse> Hotelling.UserApiSave.UserAPISoap.SaveAsync(Hotelling.UserApiSave.SaveRequest request) {
            return base.Channel.SaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotelling.UserApiSave.SaveResponse> SaveAsync(Hotelling.UserApiSave.ArrayOfString datos) {
            Hotelling.UserApiSave.SaveRequest inValue = new Hotelling.UserApiSave.SaveRequest();
            inValue.Body = new Hotelling.UserApiSave.SaveRequestBody();
            inValue.Body.datos = datos;
            return ((Hotelling.UserApiSave.UserAPISoap)(this)).SaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hotelling.UserApiSave.listResponse Hotelling.UserApiSave.UserAPISoap.list(Hotelling.UserApiSave.listRequest request) {
            return base.Channel.list(request);
        }
        
        public Hotelling.UserApiSave.ArrayOfString[] list(char X) {
            Hotelling.UserApiSave.listRequest inValue = new Hotelling.UserApiSave.listRequest();
            inValue.Body = new Hotelling.UserApiSave.listRequestBody();
            inValue.Body.X = X;
            Hotelling.UserApiSave.listResponse retVal = ((Hotelling.UserApiSave.UserAPISoap)(this)).list(inValue);
            return retVal.Body.listResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.listResponse> Hotelling.UserApiSave.UserAPISoap.listAsync(Hotelling.UserApiSave.listRequest request) {
            return base.Channel.listAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotelling.UserApiSave.listResponse> listAsync(char X) {
            Hotelling.UserApiSave.listRequest inValue = new Hotelling.UserApiSave.listRequest();
            inValue.Body = new Hotelling.UserApiSave.listRequestBody();
            inValue.Body.X = X;
            return ((Hotelling.UserApiSave.UserAPISoap)(this)).listAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hotelling.UserApiSave.validacionResponse Hotelling.UserApiSave.UserAPISoap.validacion(Hotelling.UserApiSave.validacionRequest request) {
            return base.Channel.validacion(request);
        }
        
        public Hotelling.UserApiSave.ArrayOfString validacion(string usr) {
            Hotelling.UserApiSave.validacionRequest inValue = new Hotelling.UserApiSave.validacionRequest();
            inValue.Body = new Hotelling.UserApiSave.validacionRequestBody();
            inValue.Body.usr = usr;
            Hotelling.UserApiSave.validacionResponse retVal = ((Hotelling.UserApiSave.UserAPISoap)(this)).validacion(inValue);
            return retVal.Body.validacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.validacionResponse> Hotelling.UserApiSave.UserAPISoap.validacionAsync(Hotelling.UserApiSave.validacionRequest request) {
            return base.Channel.validacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotelling.UserApiSave.validacionResponse> validacionAsync(string usr) {
            Hotelling.UserApiSave.validacionRequest inValue = new Hotelling.UserApiSave.validacionRequest();
            inValue.Body = new Hotelling.UserApiSave.validacionRequestBody();
            inValue.Body.usr = usr;
            return ((Hotelling.UserApiSave.UserAPISoap)(this)).validacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hotelling.UserApiSave.OficinasResponse Hotelling.UserApiSave.UserAPISoap.Oficinas(Hotelling.UserApiSave.OficinasRequest request) {
            return base.Channel.Oficinas(request);
        }
        
        public Hotelling.UserApiSave.ArrayOfString Oficinas() {
            Hotelling.UserApiSave.OficinasRequest inValue = new Hotelling.UserApiSave.OficinasRequest();
            inValue.Body = new Hotelling.UserApiSave.OficinasRequestBody();
            Hotelling.UserApiSave.OficinasResponse retVal = ((Hotelling.UserApiSave.UserAPISoap)(this)).Oficinas(inValue);
            return retVal.Body.OficinasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.OficinasResponse> Hotelling.UserApiSave.UserAPISoap.OficinasAsync(Hotelling.UserApiSave.OficinasRequest request) {
            return base.Channel.OficinasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotelling.UserApiSave.OficinasResponse> OficinasAsync() {
            Hotelling.UserApiSave.OficinasRequest inValue = new Hotelling.UserApiSave.OficinasRequest();
            inValue.Body = new Hotelling.UserApiSave.OficinasRequestBody();
            return ((Hotelling.UserApiSave.UserAPISoap)(this)).OficinasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hotelling.UserApiSave.AsientosResponse Hotelling.UserApiSave.UserAPISoap.Asientos(Hotelling.UserApiSave.AsientosRequest request) {
            return base.Channel.Asientos(request);
        }
        
        public Hotelling.UserApiSave.ArrayOfString Asientos(string name) {
            Hotelling.UserApiSave.AsientosRequest inValue = new Hotelling.UserApiSave.AsientosRequest();
            inValue.Body = new Hotelling.UserApiSave.AsientosRequestBody();
            inValue.Body.name = name;
            Hotelling.UserApiSave.AsientosResponse retVal = ((Hotelling.UserApiSave.UserAPISoap)(this)).Asientos(inValue);
            return retVal.Body.AsientosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.AsientosResponse> Hotelling.UserApiSave.UserAPISoap.AsientosAsync(Hotelling.UserApiSave.AsientosRequest request) {
            return base.Channel.AsientosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotelling.UserApiSave.AsientosResponse> AsientosAsync(string name) {
            Hotelling.UserApiSave.AsientosRequest inValue = new Hotelling.UserApiSave.AsientosRequest();
            inValue.Body = new Hotelling.UserApiSave.AsientosRequestBody();
            inValue.Body.name = name;
            return ((Hotelling.UserApiSave.UserAPISoap)(this)).AsientosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hotelling.UserApiSave.seatsResponse Hotelling.UserApiSave.UserAPISoap.seats(Hotelling.UserApiSave.seatsRequest request) {
            return base.Channel.seats(request);
        }
        
        public Hotelling.UserApiSave.ArrayOfString seats(int id) {
            Hotelling.UserApiSave.seatsRequest inValue = new Hotelling.UserApiSave.seatsRequest();
            inValue.Body = new Hotelling.UserApiSave.seatsRequestBody();
            inValue.Body.id = id;
            Hotelling.UserApiSave.seatsResponse retVal = ((Hotelling.UserApiSave.UserAPISoap)(this)).seats(inValue);
            return retVal.Body.seatsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.seatsResponse> Hotelling.UserApiSave.UserAPISoap.seatsAsync(Hotelling.UserApiSave.seatsRequest request) {
            return base.Channel.seatsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotelling.UserApiSave.seatsResponse> seatsAsync(int id) {
            Hotelling.UserApiSave.seatsRequest inValue = new Hotelling.UserApiSave.seatsRequest();
            inValue.Body = new Hotelling.UserApiSave.seatsRequestBody();
            inValue.Body.id = id;
            return ((Hotelling.UserApiSave.UserAPISoap)(this)).seatsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hotelling.UserApiSave.seatsSaveResponse Hotelling.UserApiSave.UserAPISoap.seatsSave(Hotelling.UserApiSave.seatsSaveRequest request) {
            return base.Channel.seatsSave(request);
        }
        
        public void seatsSave(int id, Hotelling.UserApiSave.ArrayOfString data) {
            Hotelling.UserApiSave.seatsSaveRequest inValue = new Hotelling.UserApiSave.seatsSaveRequest();
            inValue.Body = new Hotelling.UserApiSave.seatsSaveRequestBody();
            inValue.Body.id = id;
            inValue.Body.data = data;
            Hotelling.UserApiSave.seatsSaveResponse retVal = ((Hotelling.UserApiSave.UserAPISoap)(this)).seatsSave(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.seatsSaveResponse> Hotelling.UserApiSave.UserAPISoap.seatsSaveAsync(Hotelling.UserApiSave.seatsSaveRequest request) {
            return base.Channel.seatsSaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotelling.UserApiSave.seatsSaveResponse> seatsSaveAsync(int id, Hotelling.UserApiSave.ArrayOfString data) {
            Hotelling.UserApiSave.seatsSaveRequest inValue = new Hotelling.UserApiSave.seatsSaveRequest();
            inValue.Body = new Hotelling.UserApiSave.seatsSaveRequestBody();
            inValue.Body.id = id;
            inValue.Body.data = data;
            return ((Hotelling.UserApiSave.UserAPISoap)(this)).seatsSaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hotelling.UserApiSave.ReservaDatosResponse Hotelling.UserApiSave.UserAPISoap.ReservaDatos(Hotelling.UserApiSave.ReservaDatosRequest request) {
            return base.Channel.ReservaDatos(request);
        }
        
        public Hotelling.UserApiSave.ArrayOfString[] ReservaDatos(string name) {
            Hotelling.UserApiSave.ReservaDatosRequest inValue = new Hotelling.UserApiSave.ReservaDatosRequest();
            inValue.Body = new Hotelling.UserApiSave.ReservaDatosRequestBody();
            inValue.Body.name = name;
            Hotelling.UserApiSave.ReservaDatosResponse retVal = ((Hotelling.UserApiSave.UserAPISoap)(this)).ReservaDatos(inValue);
            return retVal.Body.ReservaDatosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hotelling.UserApiSave.ReservaDatosResponse> Hotelling.UserApiSave.UserAPISoap.ReservaDatosAsync(Hotelling.UserApiSave.ReservaDatosRequest request) {
            return base.Channel.ReservaDatosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hotelling.UserApiSave.ReservaDatosResponse> ReservaDatosAsync(string name) {
            Hotelling.UserApiSave.ReservaDatosRequest inValue = new Hotelling.UserApiSave.ReservaDatosRequest();
            inValue.Body = new Hotelling.UserApiSave.ReservaDatosRequestBody();
            inValue.Body.name = name;
            return ((Hotelling.UserApiSave.UserAPISoap)(this)).ReservaDatosAsync(inValue);
        }
    }
}
